SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TabCheckListUtilizacaoLog](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nm_Database] [varchar](50) NULL,
	[Log_Size] [numeric](15, 2) NULL,
	[Log_Space_Used(%)] [numeric](15, 2) NULL,
	[status_log] [int] NULL,
	[Data] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


