<<<<<<< HEAD
USE master;

ALTER AVAILABILITY GROUP <AG_NAME>
   SET (
      DTC_SUPPORT = PER_DB  
      );


/*REMOVER DTC AG */

ALTER AVAILABILITY GROUP <AG_NAME>
   SET (
      DTC_SUPPORT = NONE
=======
USE master;

ALTER AVAILABILITY GROUP <AG_NAME>
   SET (
      DTC_SUPPORT = PER_DB  
      );


/*REMOVER DTC AG */

ALTER AVAILABILITY GROUP <AG_NAME>
   SET (
      DTC_SUPPORT = NONE
>>>>>>> 8422f51c973655b14ef840885e33f280d6109d04
      );