USE MASTER
GO

DECLARE @AVAILABILITY_GROUP_NAME VARCHAR(200) = 'WorkGroup_AG'

SELECT 'STEP 1 - EXECUTAR NA REPLICA PRIMÁRIA:', 'ALTER AVAILABILITY GROUP ' + @AVAILABILITY_GROUP_NAME + ' ADD DATABASE ' + NAME 
FROM sys.databases
WHERE NAME NOT IN ('master', 'tempdb', 'model','msdb')


SELECT 'STEP 2 - EXECUTAR NA REPLICA SECUNDÁRIA:', 'ALTER DATABASE ' + NAME + ' SET HADR AVAILABILITY GROUP = ' + @AVAILABILITY_GROUP_NAME
FROM sys.databases
WHERE NAME NOT IN ('master', 'tempdb', 'model','msdb')

