USE [master]
GO

/* CRIAR O ENDPOINT EM TODAS AS RÉPLICAS QUE IRÃO FAZER PARTE DO ALWAYSON */ 

CREATE ENDPOINT [Endpoint_AvailabilityGroup] 
	STATE=STARTED
	AS TCP (LISTENER_PORT = 5022, LISTENER_IP = ALL)
	FOR DATA_MIRRORING (ROLE = ALL, AUTHENTICATION = WINDOWS NEGOTIATE
, ENCRYPTION = REQUIRED ALGORITHM AES)
GO


/* CRIAR O LOGIN E CONCEDER A PERMISSÃO EM TODAS AS RÉPLICAS. USUÁRIO QUE SERÁ UTILIZADO PARA AUTENTICAÇÃO E COMUNICAÇÃO NO ENDPOINT DO ALWAYSON */ 
CREATE LOGIN [NT AUTHORITY\ANONYMOUS LOGON] FROM WINDOWS 
WITH DEFAULT_DATABASE = [master]

GRANT CONNECT ON ENDPOINT::Endpoint_AvailabilityGroup 
TO [NT AUTHORITY\ANONYMOUS LOGON];