USE [master]

GO

ALTER AVAILABILITY GROUP [Workgroup_AG]
ADD 
REPLICA ON N'WIN2019STD03' 
WITH 
(
   ENDPOINT_URL = N'TCP://<server>:5022', 
   FAILOVER_MODE = MANUAL, 
   AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT, 
   SECONDARY_ROLE
   (
      ALLOW_CONNECTIONS = NO
   )
);
GO

/* ACESSAR CADA RÉPLICA SECUNDÁRIA E INCLUIR A RÉPLICA NO AVAILABILITY GROUP */
ALTER AVAILABILITY GROUP [Workgroup_AG] JOIN;
GO


