/* 
	OPÇÃO UTILIZADA QUANDO ALGUM OBJETO DE BANCO DE DADOS PROCEDURE, VIEW, FUNCTION FOI DELETADO.
	RECUPERA O DADO ATRAVÉS DO ARQUIVO DE BACKUP TRN GERADO SEM A NECESSIDADE DE RESTAURAÇÃO DE UMA BASE.
*/

DECLARE @Backup_Directory NVARCHAR(MAX) = '<directory>\backup.trn'

BEGIN

    DECLARE @Query VARCHAR(MAX) = '
    SELECT
        A.[Page ID],
        A.[Slot ID],
        CONVERT(VARCHAR(MAX), SUBSTRING([RowLog Contents 0], 33, LEN([RowLog Contents 0]))) AS [Script]
    FROM
        sys.fn_dump_dblog(NULL, NULL, N''DISK'', 1, ''' + @Backup_Directory + ''', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) A
    WHERE
        A.Operation = ''LOP_DELETE_ROWS''
        AND A.Context = ''LCX_MARK_AS_GHOST''                
        AND SUBSTRING([RowLog Contents 0], 33, LEN([RowLog Contents 0])) <> 0'
    
    EXEC(@Query)
END
